// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8lNJvCeYu5MRnPczKCrp0M7elhg_GSzY',
    appId: '1:849491641703:web:45233c4b0a22ae9a695bc2',
    messagingSenderId: '849491641703',
    projectId: 'stg-masjid',
    authDomain: 'stg-masjid.firebaseapp.com',
    storageBucket: 'stg-masjid.appspot.com',
    measurementId: 'G-PSST8V8Q18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAiB0-oW_NXRsV-m2z-1rAgedkAS1VE0',
    appId: '1:849491641703:android:6d5d156aeb44c415695bc2',
    messagingSenderId: '849491641703',
    projectId: 'stg-masjid',
    storageBucket: 'stg-masjid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuoQPkFHeY-Jngk62l73MsgSQp6T2NaV4',
    appId: '1:849491641703:ios:290d467ab7d7c457695bc2',
    messagingSenderId: '849491641703',
    projectId: 'stg-masjid',
    storageBucket: 'stg-masjid.appspot.com',
    iosClientId: '849491641703-ocj3ns4q0c8cg42b10g1vve8vtrulcm0.apps.googleusercontent.com',
    iosBundleId: 'com.starstechgroup.starsTechMasjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuoQPkFHeY-Jngk62l73MsgSQp6T2NaV4',
    appId: '1:849491641703:ios:771acd096dca327e695bc2',
    messagingSenderId: '849491641703',
    projectId: 'stg-masjid',
    storageBucket: 'stg-masjid.appspot.com',
    iosClientId: '849491641703-e24i8j07k608n11pdvsvpni25lt051bm.apps.googleusercontent.com',
    iosBundleId: 'com.starstechgroup.stgMasjid',
  );
}
